format = """
[](#7d41eb)\
$os\
$time\
[](bg:#8e5cf2 fg:#7d41eb)\
$directory\
[](fg:#8e5cf2 bg:#9f75f8)\
$git_branch\
$git_status\
[](fg:#9f75f8 bg:#b08dfe)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#b08dfe)
[󱞪](bold cyan) 
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#7d41eb"
disabled = false # Disabled by default
[os.symbols]
Manjaro = "[♥](bold bg:#7d41eb) "
Arch = "[󰣐](bg:#7d41eb) "
EndeavourOS = "[󰣐](bg:#7d41eb) "

[directory]
style = "bg:#8e5cf2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#9f75f8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#9f75f8"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#b08dfe"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold bg:#7d41eb"
format = '[$time ]($style)'
