[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-arc-dark-mod
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-arc-dark-mod
GtkTheme=oomox-arc-dark-mod
IconTheme=oomox-arc-dark-mod
MetacityTheme=oomox-arc-dark-mod
